### ISSUE TITLE
PersonalInfo- No validation for email filed

### ISSUE THREAD

**Issue by ChelseaChiu** [jeffmgomes/StartFinance#10]
![image](https://user-images.githubusercontent.com/45690586/55681685-5475fc00-5968-11e9-856a-094e6da117de.png)

Hi, 
Maybe need the format validation for email entry which should include character: "@"?

**Comment by kathrynfieg** [comment]
Issue resolved!
Added email address validation.

**Comment by jeffmgomes** [comment]
Resolved issue!
Added email validation.
