### ISSUE TITLE
Appointments - Update is not working properly

### ISSUE THREAD

**Issue by jeffmgomes** [jeffmgomes/StartFinance#11]
When we want to update a record the Date and Time of the Appointment is not populated in the field as expected.
The last selected date and time stay in the fields, even thought I selected a record with different date and time.

![Issue1 - Kathryn](https://user-images.githubusercontent.com/37165659/55683643-10432580-5981-11e9-8fe0-43e5096a7ff7.jpg)

**Comment by lysna87** [comment]
I had the exact same bug. The following line fixed it:
ShoppingDatePicker.Date = DateTime.Parse(((ShoppingList)ShoppingListView.SelectedItem).ShoppingDate.ToString());
You will need another line to handle TimePicker.
