### ISSUE TITLE
Appointments - No item selected in Update or Delete

### ISSUE THREAD

**Issue by jeffmgomes** [jeffmgomes/StartFinance#12]
There is no error message when we don't select any record and click on the update or delete buttons.

It should display an error message that no item was selected.

![Issue2-Kathryn](https://user-images.githubusercontent.com/37165659/55683706-ecccaa80-5981-11e9-9cdc-b88b15a10cb8.jpg)

**Comment by lysna87** [comment]
This could be related to a bug I found in my code.  After the ItemSelected event has occurred and the Update or delete has executed, the fields are cleared and the List view _looks_ as though there isn't anything selected. However the selectedItem will still be pointed to the last item selected. If you set selectedItem to "" after Update or Delete, this should trigger the warning.
![image](https://user-images.githubusercontent.com/48036336/55695589-643d2100-59f8-11e9-9b30-4005b0de23b2.png)
