### ISSUE TITLE
Shopping List - No Update function

### ISSUE THREAD

**Issue by jeffmgomes** [jeffmgomes/StartFinance#3]
It is not possible to update a shopping list record.

According to the assessment document the system must be able to update a record.

"
_Given the program in LEARN, you are required to add codes so that each function should be able to perform these core functions: 
•	create new records
•	update the existing record 
•	and delete the existing records_
"
Perhaps adding an update button next to the add button. Then the record is loaded in the fields and a button to save or cancel the editing is showed in the bar as well.

**Comment by lysna87** [comment]
Update existing record has been added. 
Also added a SelectedItemChanged event to populate the fields.
The user can then decide to update the record, delete the record, or create a new record depending on which button they click.
