### ISSUE TITLE
ContactDetails - No space between words

### ISSUE THREAD

**Issue by jeffmgomes** [jeffmgomes/StartFinance#8]
There is no space between First name, Last name and Company when we insert a new contact in the list. This can be confusing.

![Issue-Chelsea](https://user-images.githubusercontent.com/37165659/55668087-2c28c780-58ac-11e9-99c3-21b1704d37ed.jpg)

**Comment by ChelseaChiu** [comment]
Thank you for your feedback!
Have highlighted column names to display the information properly.
See the image below:
![image](https://user-images.githubusercontent.com/45690586/55676854-34205000-591c-11e9-8c63-99be760453fa.png)

**Comment by jeffmgomes** [comment]
All good. You can merge with the master now.
