### ISSUE TITLE
ContactDetails - Phone number allowing letters

### ISSUE THREAD

**Issue by jeffmgomes** [jeffmgomes/StartFinance#9]
The Phone field is accepting letters. As example I added a phone numer "AAAAAAAA" and it allowed me to do it.

![Issue2-Chelsea](https://user-images.githubusercontent.com/37165659/55668126-a22d2e80-58ac-11e9-908d-a3a7859f9875.jpg)

**Comment by ChelseaChiu** [comment]
Thank you!
Bug has been fixed.
The mobilePhone data type has been changed from string to integer.
Also, when users try to input non-numeric data into phone textbox filed then add/update to the database, the system will catch format exception and pop up prompt-box.
![image](https://user-images.githubusercontent.com/45690586/55677041-0f2ddc00-5920-11e9-84c5-b5a5c7a9d759.png)

**Comment by jeffmgomes** [comment]
All good. You can merge with the master now.
